name: test_bambu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_database: ^10.0.13
  equatable: ^2.0.5
  expandable: ^5.0.1
  url_launcher: ^6.1.9
  card_swiper: ^2.0.4
  sliver_tools: ^0.2.9


  flutter:
    sdk: flutter

  firebase_auth_service:
    path: "packages/firebase_auth_service"

  news_repository:
    path: "packages/news_repository"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
