name: test_bambu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_database: ^10.0.13
  equatable: ^2.0.5
  flutter_advanced_drawer: ^1.3.3


  flutter:
    sdk: flutter

  firebase_auth_service:
    path: "packages/firebase_auth_service"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
