name: firebase_auth_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_database: ^10.0.13
  google_sign_in: ^5.4.4
  equatable: ^2.0.5

  news_repository:
    path: "../news_repository"


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  # very_good_analysis: ^4.0.0
