// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkH2MeJIgBkqTZp8HP7Ulthk6zRDN9gK0',
    appId: '1:547831389528:android:27c04a896ace3e59e1592d',
    messagingSenderId: '547831389528',
    projectId: 'test-bambu',
    databaseURL: 'https://test-bambu-default-rtdb.firebaseio.com',
    storageBucket: 'test-bambu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsSUuvt1eUwa8Hs82ZiSxkBB9eN4tDoI8',
    appId: '1:547831389528:ios:c8910bbf75cd7e16e1592d',
    messagingSenderId: '547831389528',
    projectId: 'test-bambu',
    databaseURL: 'https://test-bambu-default-rtdb.firebaseio.com',
    storageBucket: 'test-bambu.appspot.com',
    androidClientId: '547831389528-pnco2j1ieqou24n72kkgv104fihl2v0t.apps.googleusercontent.com',
    iosClientId: '547831389528-bvmv0s3un777tequvhrr6gsujqt4gujp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testBambu',
  );
}
